 #Dictionnaires EX5 PY P1

nouvelle_campagne = {
"responsable_de_campagne": "Jeanne d'Arc",
"nom_de_campagne": "Campagne nous aimons les chiens",
"date_de_début": "01/01/2020",
"influenceurs_importants": ["@MonAmourDeChien", "@MeilleuresFriandisesPourChiens"]
}

print(nouvelle_campagne)

nouvelle_campagne["test"] = "Cet un exo pour comprendre les dictionnaires."

print(nouvelle_campagne)

nouvelle_campagne["Test2"] = " Je viens d'ajouter une nouvelle  paire cle-valeur dont [test2] est la val "